### PR TITLE
Some type related fixes

### PR DESCRIPTION
**Pull request by bapt**

### CODE REVIEW

**Review by mpieuchot — COMMENTED** [review]
Please include the warnings you're talking about.  It's hard to comment without them.

However I'm surprised that z_stream's `total_out' is of type size_t (well uLong) on FreeBSD.  The difference might be that OpenBSD ships zlib v1.2.3 while FreeBSD is still stuck with v1.0.4.

**Comment by bapt** [comment]
FreeBSD ships with zlib 1.2.11 and total_out is uLong

Sure next time I will list the warnings sorry

**Comment by mpieuchot** [comment]
Ok then the issue comes from OpenBSD's zlib version, I'll see how to fix that.

I assumed FreeBSD still use 1.0.4 because of this file btw:
  https://svnweb.freebsd.org/base/head/sys/sys/zlib.h?view=markup#l247

**Comment by bapt** [comment]
this is the version in kernel, the version in userland is not the same (yeah duplication that needs to be fixed)

**Pull request closed without merging**
